fixtures:
  repositories:
    apt: https://github.com/puppetlabs/puppetlabs-apt.git
    epel: https://github.com/voxpupuli/puppet-epel.git
    logrotate: https://github.com/voxpupuli/puppet-logrotate.git
    rpmkey: https://github.com/stschulte/puppet-rpmkey.git
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    yumrepo_core: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
    zypprepo: https://github.com/voxpupuli/puppet-zypprepo.git
    systemd: https://github.com/voxpupuli/puppet-systemd.git
